version: '3.8'

services:
  # The Math Engine service
  detector:
    build:
      context: .
      dockerfile: Dockerfile.detector
    container_name: aegis_brain
    volumes:
      # This CONNECTS your Mac's 'logs' folder to the Container's 'logs' folder
      - ./logs:/app/logs
      # This CONNECTS your Mac's 'src' folder so you can edit code live
      - ./src:/app/src
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - aegis_net

networks:
  aegis_net:
    driver: bridge