version: '3.8'

services:
  # THE BRAIN
  detector:
    build:
      context: .
      dockerfile: Dockerfile.detector
    container_name: aegis_brain
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - aegis_net

  # THE SENSOR
  sensor:
    build:
      context: .
      dockerfile: Dockerfile.sensor
    container_name: aegis_sensor
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app/src
    networks:
      - aegis_net
    depends_on:
      - detector
      
networks:
  aegis_net:
    driver: bridge